# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Message'), (2, 'Join'), (3, 'Leave')], default=0)),
                ('source', models.CharField(max_length=100)),
                ('source_raw', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('target_raw', models.CharField(max_length=100)),
                ('sent', models.DateTimeField()),
                ('received', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
