# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webirc', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRCScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IRCServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=6667)),
                ('ssl', models.BooleanField(default=False)),
                ('ipv6', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=128)),
                ('nickname', models.CharField(max_length=100)),
                ('realname', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
