# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webirc', '0003_ircscreen_ircserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ircserver',
            name='ipv6',
        ),
    ]
