# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webirc', '0005_auto_20170703_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRCScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webirc.Screen')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webirc.IRCServer')),
            ],
            options={
                'verbose_name': 'IRC screen',
            },
        ),
    ]
