# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webirc', '0006_ircscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ircscreen',
            name='topic',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
