# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webirc', '0007_ircscreen_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterExitEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Join'), (2, 'Leave'), (3, 'Kick')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='received',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
        migrations.RemoveField(
            model_name='event',
            name='source_raw',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_raw',
        ),
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
        migrations.AddField(
            model_name='event',
            name='moment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webirc.Screen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Message'), (2, 'Enter/Exit')], default=0),
        ),
    ]
