# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webirc', '0008_auto_20170705_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnterExitEvent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='screen',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
