# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webirc', '0011_remove_message_screen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='moment',
        ),
    ]
