# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webirc', '0012_remove_message_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterexitevent',
            name='source',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enterexitevent',
            name='target',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
