# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webirc', '0013_auto_20170705_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterexitevent',
            name='target',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
