# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webirc', '0015_auto_20170705_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(0, 'Privmsg'), (1, 'Notice')], default=0),
        ),
        migrations.AlterField(
            model_name='enterexitevent',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Join'), (2, 'Part'), (3, 'Kick'), (4, 'Quit')], default=0),
        ),
    ]
